name: mid_term_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    firebase_core: ^3.6.0
    cloud_firestore: ^5.4.4
    flutter:
        sdk: flutter
    image_picker: ^1.1.2
    random_string: ^2.3.1
    fluttertoast: ^8.2.8
    file_picker: ^8.1.2
    firebase_storage: ^12.3.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
